vim.pack.add({ "https://github.com/christoomey/vim-tmux-navigator" })
vim.keymap.set({ "n", "v" }, "<c-h>", "<cmd>TmuxNavigateLeft<cr>")
vim.keymap.set({ "n", "v" }, "<c-j>", "<cmd>TmuxNavigateDown<cr>")
vim.keymap.set({ "n", "v" }, "<c-k>", "<cmd>TmuxNavigateUp<cr>")
vim.keymap.set({ "n", "v" }, "<c-l>", "<cmd>TmuxNavigateRight<cr>")
vim.keymap.set("t", "<c-h>", "<C-w><cmd>TmuxNavigateLeft<cr>")
vim.keymap.set("t", "<c-j>", "<C-w><cmd>TmuxNavigateDown<cr>")
vim.keymap.set("t", "<c-k>", "<C-w><cmd>TmuxNavigateUp<cr>")
vim.keymap.set("t", "<c-l>", "<C-w><cmd>TmuxNavigateRight<cr>")
vim.g.tmux_navigator_no_mappings = 1
